--- 
cache: 
  paths: 
    - node_modules/
image: "node:latest"
default:
  before_script:
    - cd backend
install_dependencies: 
  stage: setup
  artifacts: 
    paths: 
      - node_modules/
  script: 
    - "npm install"
execute_tests: 
  before_script:
      - npm install jest
  stage: test
  script: "npm test -- --updateSnapshot --passWithNoTests"
build_project:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
stages:
  - setup
  - test
  - build

