--- 
cache: 
  paths: 
    - backend/node_modules/
image: "node:latest"
install_dependencies: 
  artifacts: 
    paths: 
      - backend/node_modules/
  script: 
    - "npm install"
  stage: build
stages: 
  - build
  - test
testing_testing: 
  script: "npm test -- --updateSnapshot --passWithNoTests"
  stage: test
