--- 
image: "node:latest"
default:
  before_script:
    - cd backend
    - npm install
install_dependencies: 
  stage: setup
  artifacts: 
    paths: 
      - node_modules/
  script: 
    - npm install
build_project:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
      - node_modules/
execute_tests:
  stage: test
  script: npm test -- --updateSnapshot --passWithNoTests
stages:
  - setup
  - build
  - test