--- 
cache: 
  paths: 
    - node_modules/
image: "node:latest"
default:
  before_script:
    - cd backend
install_dependencies: 
  stage: setup
  artifacts: 
    paths: 
      - node_modules/
  script: 
    - "npm install"
build_project:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
      - node_modules/
execute_tests:
  stage: test
  before_script:
      - npm install jest
      - cd backend
  script: "npm test -- --updateSnapshot --passWithNoTests"
stages:
  - setup
  - build
  - test